services:
  reverse-proxy:
    image: traefik:3.1.6
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
  hello-world-semel:
    build: .
    container_name: hello-world-semel
    volumes:
      - ./hello-world-semel:/www
    labels:
      - traefik.http.routers.hello-world-semel.rule=Host(`helloworld.docker.localhost`) && PathPrefix(`/semel`)
      - traefik.http.routers.hello-world-semel.middlewares=strip-app-prefixes@file
      - traefik.http.services.hello-world-semel.loadbalancer.server.port=8000
  hello-world-bis:
    build: .
    container_name: hello-world-bis
    volumes:
      - ./hello-world-bis:/www
    labels:
      - traefik.http.routers.hello-world-bis.rule=Host(`helloworld.docker.localhost`) && PathPrefix(`/bis`)
      - traefik.http.routers.hello-world-bis.middlewares=strip-app-prefixes@file
      - traefik.http.services.hello-world-bis.loadbalancer.server.port=8000